# Generated by Django 4.2.6 on 2023-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Log',
            },
        ),
    ]
